# Generated by Django 5.2.8 on 2026-02-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_approved_status'),
        ('orders', '0003_orderitem_atributos'),
    ]

    operations = [
    ]
