# Generated by Django 5.2.8 on 2026-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20260209_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('approved', 'Aprobado'), ('pending_payment', 'Falta pago'), ('draft', 'Borrador'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='created', max_length=20),
        ),
    ]
