# Generated by Django 5.2.8 on 2026-03-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de pedido', 'verbose_name_plural': 'Items de pedido'},
        ),
    ]
