# Generated by Django 5.2.8 on 2026-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_label_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product__categoria__nombre', 'product__nombre'], 'verbose_name': 'Item de pedido', 'verbose_name_plural': 'Items de pedido'},
        ),
    ]
