# Generated by Django 5.2.8 on 2026-09-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido pagado',
                'verbose_name_plural': 'Pedidos pagados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
