# Generated by Django 5.2.8 on 2026-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_allow_manual_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeliveryOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido pendiente a entregar',
                'verbose_name_plural': 'Pendientes a entregar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Creado'), ('approved', 'Aprobado'), ('pending_payment', 'Falta pago'), ('draft', 'Borrador'), ('paid', 'Pagado'), ('shipped', 'Pendiente a entregar'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='created', max_length=20),
        ),
    ]
