# Generated by Django 5.2.8 on 2026-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
