# Generated by Django 5.2.8 on 2026-02-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_atributos_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('category_tile', 'Explora por categoria')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Imagen Home',
                'verbose_name_plural': 'Imagenes Home',
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
