# Generated by Django 5.2.8 on 2026-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('category_tile', 'Explora por categoria'), ('featured_collection', 'Colecciones destacadas')], max_length=20),
        ),
    ]
