# Generated by Django 5.2.8 on 2026-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_homeimage_target_url_alter_homeimage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
