# Generated by Django 5.2.8 on 2026-03-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='homemarquee',
            options={'verbose_name': 'Franja Home', 'verbose_name_plural': 'Franjas Home'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
