# Generated by Django 5.2.8 on 2026-03-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_options_alter_homemarquee_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
