# Generated by Django 5.2.8 on 2026-03-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_delete_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=40)),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='supplier_contacts/files/')),
                ('revisado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto de proveedor',
                'verbose_name_plural': 'Contactos de proveedores',
                'ordering': ['-creado_en'],
            },
        ),
    ]
