# Generated by Django 5.2.8 on 2026-04-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
