# Generated by Django 5.2.8 on 2026-04-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_seed_ofertas_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
