# Generated by Django 5.2.8 on 2026-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sin_stock',
            field=models.BooleanField(default=False),
        ),
    ]
