# Generated by Django 5.2.8 on 2026-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_product_sin_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='atributos_sin_stock',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
