# Generated by Django 5.2.8 on 2026-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_atributos_sin_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='mostrar_precios_invitados',
            field=models.BooleanField(default=True, help_text='Si está activo, los usuarios sin iniciar sesión podrán ver los precios de los productos.', verbose_name='Mostrar precios a invitados'),
        ),
    ]
