# Generated by Django 5.2.8 on 2026-08-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_storesettings_mostrar_precios_invitados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
