# Generated by Django 5.2.8 on 2026-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_storesettings_mostrar_precios_invitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='Disculpa las molestias. Estamos realizando mejoras y volveremos pronto.', verbose_name='Mensaje de mantenimiento'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Bloquea la tienda para clientes e invitados sin cerrar sus sesiones. El equipo interno conserva el acceso.', verbose_name='Modo mantenimiento activo'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_title',
            field=models.CharField(blank=True, default='Estamos en mantenimiento', max_length=120, verbose_name='Titulo de mantenimiento'),
        ),
    ]
