# Generated by Django 5.2.8 on 2026-03-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_approval_status'),
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
    ]
