# Generated by Codex on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_password_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="ultima clave cambiada el"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="welcome_email_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="bienvenida enviada el"),
        ),
    ]
