# Generated by Django 5.2.8 on 2026-07-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='debe cambiar clave'),
        ),
    ]
