# Generated by Django 5.2.8 on 2026-08-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_storesettings_mostrar_precios_invitados'),
        ('users', '0012_customuser_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStoreSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.storesettings',),
        ),
    ]
