# Generated by Django 5.2.8 on 2026-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_globalstoresettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('operator', 'Operador'), ('admin', 'Administrador')], default='user', max_length=10, verbose_name='rol'),
        ),
    ]
